# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:
- task: TerraformTaskV4@4
  displayName: Terraform Init
  inputs:
    provider: 'azurerm'
    command: 'init'
    backendServiceArm: 'Ravi@akshaysharmaji'
    backendAzureRmResourceGroupName: 'automate'
    backendAzureRmStorageAccountName: 'autostore123'
    backendAzureRmContainerName: 'autostate'
    backendAzureRmKey: 'azure.tfstate'

- task: TerraformTaskV4@4
  displayName: Terraform Plan
  inputs:
    provider: 'azurerm'
    command: 'plan'
    environmentServiceNameAzureRM: 'Ravi@akshaysharmaji'
